PlayRoom/Controllers/AccessoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service.Service.Interfaces;
using Service.ViewModels.Favorites;

namespace PlayRoom.Controllers
{
    public class AccessoriesController : Controller
    {
        private readonly IAccessoryService _accessoryService;
        private readonly ICategoryService _categoryService;
        private readonly IHttpContextAccessor _contextAccessor;
        public AccessoriesController(IAccessoryService accessoryService,
                               ICategoryService categoryService,
                               IHttpContextAccessor contextAccessor)
        {
            _accessoryService = accessoryService;
            _categoryService = categoryService;
            _contextAccessor = contextAccessor;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? category, string? priceRange, string? orderBy, int? page = 1)
        {
            if (page == null) return BadRequest();

            ViewBag.SelectedCategory = category;
            ViewBag.SelectedPriceRange = priceRange;
            ViewBag.SelectedOrderBy = orderBy;

            if (page < 1) page = 1;
            var data = await _accessoryService.GetAllPaginated((int)page, 8, category, priceRange, orderBy);

            var categories = await _categoryService.GetAllAsync();

            ViewBag.Category = categories;


            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();

            return View(data);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();
            var existData = await _accessoryService.GetByIdAsync((int)id);
            if (existData == null) return NotFound();

            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();

            return View(existData);
        }
    }
}

PlayRoom/Controllers/ConsolesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service.Service.Interfaces;
using Service.ViewModels.Favorites;

namespace PlayRoom.Controllers
{
    public class ConsolesController : Controller
    {
        private readonly IConsoleService _consoleService;
        private readonly ICategoryService _categoryService;
        private readonly IHttpContextAccessor _contextAccessor;
        public ConsolesController(IConsoleService consoleService,ICategoryService categoryService, IHttpContextAccessor contextAccessor)
        {
            _consoleService = consoleService;
            _categoryService = categoryService;
            _contextAccessor = contextAccessor;
        }

        public async Task<IActionResult> Index(List<string>? category, string? priceRange, string? orderBy, int? page = 1)
        {
            if (page == null) return BadRequest();

            ViewBag.SelectedCategory = category;
            ViewBag.SelectedPriceRange = priceRange;
            ViewBag.SelectedOrderBy = orderBy;

            if (page < 1) page = 1;
            var data = await _consoleService.GetAllPaginated((int)page, category, 8, priceRange, orderBy);

            var categories = await _categoryService.GetAllAsync();

            ViewBag.Category = categories;

            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();

            return View(data);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();
            var existData = await _consoleService.GetByIdAsync((int)id);
            if (existData == null) return NotFound();

            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();

            return View(existData);
        }
    }
}

PlayRoom/Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service.Service.Interfaces;
using Service.ViewModels.Favorites;
using System.Threading.Tasks;

namespace PlayRoom.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGameService _gameService;
        private readonly ICategoryService _categoryService;
        private readonly IHttpContextAccessor _contextAccessor;
        public GamesController(IGameService gameService, 
                               ICategoryService categoryService,
                               IHttpContextAccessor contextAccessor)
        {
            _gameService = gameService;
            _categoryService = categoryService;
            _contextAccessor = contextAccessor;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? category, string? priceRange, string? orderBy, int? page = 1)
        {
            if (page == null) return BadRequest();

            ViewBag.SelectedCategory = category;
            ViewBag.SelectedPriceRange = priceRange;
            ViewBag.SelectedOrderBy = orderBy;

            if (page < 1) page = 1;
            var data = await _gameService.GetAllPaginated((int)page, 8, category, priceRange, orderBy);

            var categories = await _categoryService.GetAllAsync();

            ViewBag.Category = categories;

            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();


            return View(data);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null) return BadRequest();
            var existData = await _gameService.GetByIdAsync((int)id);
            if (existData == null) return NotFound();

            List<FavoritesVM> favoriteDatas = new();
            if (_contextAccessor.HttpContext.Request.Cookies["favorites"] != null)
            {
                favoriteDatas = JsonConvert.DeserializeObject<List<FavoritesVM>>(_contextAccessor.HttpContext.Request.Cookies["favorites"]);
            }

            ViewBag.Favorites = favoriteDatas
                .Select(f => (f.ProductId, f.ProductType))
                .ToList();
            return View(existData);
        }

    }
}

PlayRoom/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Service.Interfaces;
using Service.ViewModels;
using System.Threading.Tasks;

namespace PlayRoom.Controllers
{
    public class SearchController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IConsoleService _consoleService;
        private readonly IAccessoryService _accessoryService;
        public SearchController(IGameService gameService, 
                                IConsoleService consoleService, 
                                IAccessoryService accessoryService)
        {
            _gameService = gameService;
            _consoleService = consoleService;
            _accessoryService = accessoryService;
        }
        public async Task<IActionResult> Index(string? searchText)
        {
            if (searchText == null) return NotFound();
            var games = await _gameService.GetAllAsync();
            var consoles = await _consoleService.GetAllAsync();
            var accessories = await _accessoryService.GetAllAsync();

            var keyword = searchText.ToLower().Trim();

            var filteredGames = games.Where(m => m.Name.ToLower().Trim().Contains(keyword)).ToList();
            var filteredConsoles = consoles.Where(m => m.Name.ToLower().Trim().Contains(keyword)).ToList();
            var filteredAccessories = accessories.Where(m => m.Name.ToLower().Trim().Contains(keyword)).ToList();


            SearchVM model = new SearchVM()
            {
                Accessories= filteredAccessories,
                Consoles = filteredConsoles,
                Games= filteredGames
            };
            return View(model);
        }

    }
}

PlayRoom/Views/Search/Index.cshtml
@model SearchVM

@section css {
    <link rel="stylesheet" href="~/assets/css/games/games.css">
}

<main class="pb-5">
    <section id="main-top">
        <div class="container-xxl">
            <div class="path">
                <a asp-controller="home" asp-action="index">Ana səhifə</a>
                <span> > </span>
                <a asp-controller="games" asp-action="index">Oyunlar</a>
            </div>
            <div class="page-topic">
                <h3>Axtarış nəticələri</h3>
            </div>
            <div class="products">
                <div class="row">
                    @if (Model.Accessories.Any())
                    {
                        @foreach (var item in Model.Accessories)
                        {
                            <div class="col-lg-3 col-6 product">
                                <div class="card-main">
                                    <div class="card-top">
                                        <a asp-controller="Accessories" asp-action="Detail" asp-route-id="@item.Id">
                                            <img src="~/assets/images/Accessories/@item.Images.FirstOrDefault(m=>m.IsMain==true).Name" alt="">
                                        </a>
                                        @if (item.CreatedDate > DateTime.Now.AddYears(-1))
                                        {
                                            <div class="new">
                                                <span>YENI</span>
                                            </div>
                                        }
                                        @if (item.Discounts != null && item.Discounts.Any())
                                        {
                                            <div class="discount">
                                                <span>ENDIRIM</span>
                                            </div>
                                        }
                                        <div class="like">
                                            <i class="fa-solid fa-heart"></i>
                                        </div>

                                    </div>
                                    <div class="card-bottom">
                                        <div class="game-name">
                                            <a href="">
                                                @item.Name
                                                @if (item.Category.Any())
                                                {
                                                    @($" ({string.Join(", ", item.Category.Select(c => c.Name))})")
                                                }
                                            </a>
                                        </div>

                                        <div class="game-price mt-4">
                                            @if (item.Category != null && item.Category.Any())
                                            {
                                                <span class="old-price">@item.Price.ToString("F0") ₼</span>


                                                decimal discountedPrice = item.Price;
                                                foreach (var discount in item.Discounts)
                                                {
                                                    discountedPrice *= (1 - discount.Value / 100);
                                                }


                                                <span class="price">@discountedPrice.ToString("F0") ₼</span>
                                            }
                                            else
                                            {
                                                <span class="price">@item.Price.ToString("F0") ₼</span>
                                            }
                                        </div>

                                    </div>
                                    <div class="add-basket">
                                        <button class="add-basket-btn" type="submit" product-type="game" data-id="@item.Id">SƏBƏTƏ AT</button>
                                    </div>
                                </div>
                            </div>
                        }

                    }

                    @if (Model.Games.Any())
                    {
                        @foreach (var item in Model.Games)
                        {
                            <div class="col-lg-3 col-6 product">
                                <div class="card-main">
                                    <div class="card-top">
                                        <a asp-controller="Games" asp-action="Detail" asp-route-id="@item.Id">
                                            <img src="~/assets/images/Game-Images/@item.GameImages.FirstOrDefault(m=>m.IsMain==true).Name" alt="">
                                        </a>
                                        @if (item.CreatedDate > DateTime.Now.AddYears(-1))
                                        {
                                            <div class="new">
                                                <span>YENI</span>
                                            </div>
                                        }
                                        @if (item.GameDiscounts != null && item.GameDiscounts.Any())
                                        {
                                            <div class="discount">
                                                <span>ENDIRIM</span>
                                            </div>
                                        }
                                        <div class="like">
                                            <i class="fa-solid fa-heart"></i>
                                        </div>

                                    </div>
                                    <div class="card-bottom">
                                        <div class="game-name">
                                            <a href="">
                                                @item.Name
                                                @if (item.GameCategory.Any())
                                                {
                                                    @($" ({string.Join(", ", item.GameCategory.Select(c => c.Name))})")
                                                }
                                            </a>
                                        </div>

                                        <div class="game-price mt-4">
                                            @if (item.GameDiscounts != null && item.GameDiscounts.Any())
                                            {
                                                <span class="old-price">@item.Price.ToString("F0") ₼</span>


                                                decimal discountedPrice = item.Price;
                                                foreach (var discount in item.GameDiscounts)
                                                {
                                                    discountedPrice *= (1 - discount.Value / 100);
                                                }


                                                <span class="price">@discountedPrice.ToString("F0") ₼</span>
                                            }
                                            else
                                            {
                                                <span class="price">@item.Price.ToString("F0") ₼</span>
                                            }
                                        </div>

                                    </div>
                                    <div class="add-basket">
                                        <button class="add-basket-btn" type="submit" product-type="game" data-id="@item.Id">SƏBƏTƏ AT</button>
                                    </div>
                                </div>
                            </div>
                        }

                    }

                    @if (Model.Consoles.Any())
                    {
                        @foreach (var item in Model.Consoles)
                        {
                            <div class="col-lg-3 col-6 product">
                                <div class="card-main">
                                    <div class="card-top">
                                        <a asp-controller="Consoles" asp-action="Detail" asp-route-id="@item.Id">
                                            <img src="~/assets/images/Console-Images/@item.Images.FirstOrDefault(m=>m.IsMain==true).Name" alt="">
                                        </a>
                                        @if (item.CreatedDate > DateTime.Now.AddYears(-1))
                                        {
                                            <div class="new">
                                                <span>YENI</span>
                                            </div>
                                        }
                                        @if (item.Discounts != null && item.Discounts.Any())
                                        {
                                            <div class="discount">
                                                <span>ENDIRIM</span>
                                            </div>
                                        }
                                        <div class="like">
                                            <i class="fa-solid fa-heart"></i>
                                        </div>

                                    </div>
                                    <div class="card-bottom">
                                        <div class="game-name">
                                            <a href="">
                                                @item.Name
                                                @if (item.Categories.Any())
                                                {
                                                    @($" ({string.Join(", ", item.Categories.Select(c => c.Name))})")
                                                }
                                            </a>
                                        </div>

                                        <div class="game-price mt-4">
                                            @if (item.Categories != null && item.Categories.Any())
                                            {
                                                <span class="old-price">@item.Price.ToString("F0") ₼</span>


                                                decimal discountedPrice = item.Price;
                                                foreach (var discount in item.Discounts)
                                                {
                                                    discountedPrice *= (1 - discount.Value / 100);
                                                }


                                                <span class="price">@discountedPrice.ToString("F0") ₼</span>
                                            }
                                            else
                                            {
                                                <span class="price">@item.Price.ToString("F0") ₼</span>
                                            }
                                        </div>

                                    </div>
                                    <div class="add-basket">
                                        <button class="add-basket-btn" type="submit" product-type="console" data-id="@item.Id">SƏBƏTƏ AT</button>
                                    </div>
                                </div>
                            </div>
                        }

                    }

                </div>
            </div>

        </div>
    </section>
</main>

@section js {
    <script src="~/assets/js/games.js"></script>
    <script src="~/assets/js/basket.js"></script>
}